baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Falek Miah Blog'
description = "Falek Miah Personal Blog"
author = "Falek Miah"
theme = "somrat"

# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"

# disable language
# disableLanguages = [] # disable language from here
# google analutics
# googleAnalytics = "" # example : UA-123-45
# disqus short name
# disqusShortname = "" # get your shortname form here : https://disqus.com


############################## Outputs ###############################
[outputs]
home = ["HTML"]

[markup.goldmark.renderer]
unsafe= true

############################## Plugins ###############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
[[params.plugins.css]]
link = "plugins/hover/hover.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"

############################## default parameters ###############################
[params]
logo_light = "images/logo-FalekMiah-light.png"
logo_dark = "images/logo-FalekMiah-dark.png"
logo_width = "150px"
favicon = "images/logo-FalekMiah-light.png"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.
  
############################## social site ###############################

[[params.social]]
icon = "fab fa-twitter"
#icon = "images/icons/coffee.png"
link = "https://twitter.com/FalekMiah"

[[params.social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/falekmiah/"

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/FalekMiah01"

#[[params.social]]
#icon = "fas fa-envelope-square"
#link = "mailto:falekmiah@hotmail.co.uk"


############################## language ###############################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright Falek Miah &copy; 2021"

############################## navigation ###############################

# main menu
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About me"
pre = "#"
url = "about"
weight = 2

[[Languages.en.menu.main]]
name = "Blog"
url = "blog"
weight = 3


#[[Languages.en.menu.main]]
#name = "Service"
#pre = "#"
#url = "service"
#weight = 3

#[[Languages.en.menu.main]]
#name = "Portfolio"
#pre = "#"
#url = "portfolio"
#weight = 4

#[[Languages.en.menu.main]]
#name = "Testimonial"
#pre = "#"
#url = "testimonial"
#weight = 5

#[[Languages.en.menu.main]]
#name = "Contact"
#pre = "#"
#url = "contact"
#weight = 6



